### ISSUE TITLE
Implement Datalogging (magnet) for health / tracking device

### ISSUE THREAD

**Issue by truedat101** [IoTone/ProjectMagNET#13]
- [ ] For temperature / baro sensor
- [ ] for earthquake detector
- [ ] for head tracker
- [ ] for light sensor
